# Generated by Django 3.2.15 on 2025-02-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("hardware", "0013_hardware_credits")]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="max_per_team",
            field=models.IntegerField(default=999, null=True),
        ),
        migrations.AlterField(
            model_name="hardware",
            name="max_per_team",
            field=models.IntegerField(default=999, null=True),
        ),
    ]
